import { MigrationInterface, QueryRunner } from "typeorm";

export class AddMissingTables1762920736777 implements MigrationInterface {
    name = 'AddMissingTables1762920736777'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "family_members" DROP CONSTRAINT "FK_family_members_family_group_id"`);
        await queryRunner.query(`ALTER TABLE "family_members" DROP CONSTRAINT "FK_family_members_user_id"`);
        await queryRunner.query(`ALTER TABLE "family_members" DROP CONSTRAINT "FK_family_members_added_by_user_id"`);
        await queryRunner.query(`ALTER TABLE "family_groups" DROP CONSTRAINT "FK_family_groups_head_user_id"`);
        await queryRunner.query(`ALTER TABLE "family_groups" DROP CONSTRAINT "FK_family_groups_plan_id"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_subscriptions_user_id"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_subscriptions_plan_id"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_subscriptions_payment_id"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payments_user_id"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payments_provider_id"`);
        await queryRunner.query(`ALTER TABLE "user_profiles" DROP CONSTRAINT "FK_user_profiles_user_id"`);
        await queryRunner.query(`ALTER TABLE "device_tokens" DROP CONSTRAINT "FK_device_tokens_user_id"`);
        await queryRunner.query(`ALTER TABLE "access_codes" DROP CONSTRAINT "FK_access_codes_creator_user_id"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP CONSTRAINT "FK_wallet_transactions_wallet_id"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_wallets_user_id"`);
        await queryRunner.query(`CREATE TABLE "services" ("service_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_019d74f7abcdcb5a0113010cb03" UNIQUE ("name"), CONSTRAINT "PK_ef0531b9789b488593690ab8d5d" PRIMARY KEY ("service_id"))`);
        await queryRunner.query(`CREATE TABLE "provider_photos" ("provider_photo_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "provider_id" uuid NOT NULL, "image_url" character varying NOT NULL, "uploaded_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_de038a468aca3e6dc5eb133ee19" PRIMARY KEY ("provider_photo_id"))`);
        await queryRunner.query(`CREATE TABLE "provider_reviews" ("provider_review_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "provider_id" uuid NOT NULL, "reviewer_name" character varying NOT NULL, "rating" integer NOT NULL DEFAULT '0', "comment" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fbeddcc8eed4922992cce79e72a" PRIMARY KEY ("provider_review_id"))`);
        await queryRunner.query(`CREATE TABLE "providers" ("provider_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "service_id" uuid NOT NULL, "admin_user_id" uuid NOT NULL, "estate_id" uuid NOT NULL, "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "phone" character varying NOT NULL, "location" character varying NOT NULL, "availability" character varying, "bio" character varying, "skill" character varying, "profile_picture_url" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e5f817b362ee59803255e347fae" PRIMARY KEY ("provider_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."utility_providers_category_enum" AS ENUM('power', 'water', 'waste', 'gas', 'internet')`);
        await queryRunner.query(`CREATE TABLE "utility_providers" ("utility_provider_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "category" "public"."utility_providers_category_enum" NOT NULL, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8cc872ea1f05274d9311608c401" PRIMARY KEY ("utility_provider_id"))`);
        await queryRunner.query(`CREATE TABLE "utility_payments" ("utility_payment_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "utility_bill_id" uuid NOT NULL, "payment_id" uuid NOT NULL, "amount" numeric(10,2) NOT NULL, "paid_at" TIMESTAMP NOT NULL, CONSTRAINT "PK_e54b90b3dcf760d3492caabfce1" PRIMARY KEY ("utility_payment_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."utility_bills_status_enum" AS ENUM('unpaid', 'paid', 'overdue')`);
        await queryRunner.query(`CREATE TABLE "utility_bills" ("utility_bill_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "utility_account_id" uuid NOT NULL, "billing_period_start" TIMESTAMP NOT NULL, "billing_period_end" TIMESTAMP NOT NULL, "amount_due" numeric(10,2) NOT NULL, "due_date" TIMESTAMP NOT NULL, "status" "public"."utility_bills_status_enum" NOT NULL DEFAULT 'unpaid', "generated_at" TIMESTAMP NOT NULL, "metadata" jsonb, CONSTRAINT "PK_a0ec42b89dd269564fa94c1fe2c" PRIMARY KEY ("utility_bill_id"))`);
        await queryRunner.query(`CREATE TABLE "utility_accounts" ("utility_account_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "estate_id" uuid NOT NULL, "utility_provider_id" uuid NOT NULL, "account_number" character varying NOT NULL, "address" character varying NOT NULL, "is_default" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c50b7d7e497e81127a046cb605c" PRIMARY KEY ("utility_account_id"))`);
        await queryRunner.query(`CREATE TABLE "message_reactions" ("reaction_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "message_id" uuid NOT NULL, "user_id" uuid NOT NULL, "emoji" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6642c38294074af0d8184bb3a2d" PRIMARY KEY ("reaction_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."messages_type_enum" AS ENUM('text', 'image', 'file', 'voice', 'link_preview', 'system')`);
        await queryRunner.query(`CREATE TYPE "public"."messages_status_enum" AS ENUM('queued', 'sent', 'delivered', 'read')`);
        await queryRunner.query(`CREATE TABLE "messages" ("message_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversation_id" uuid NOT NULL, "sender_user_id" uuid NOT NULL, "type" "public"."messages_type_enum" NOT NULL DEFAULT 'text', "content" character varying, "metadata" jsonb, "reply_to_message_id" uuid, "status" "public"."messages_status_enum" NOT NULL DEFAULT 'queued', "edited_at" TIMESTAMP, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6187089f850b8deeca0232cfeba" PRIMARY KEY ("message_id"))`);
        await queryRunner.query(`CREATE TABLE "conversation_participants" ("participant_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversation_id" uuid NOT NULL, "user_id" uuid NOT NULL, "is_admin" boolean NOT NULL DEFAULT false, "is_muted" boolean NOT NULL DEFAULT false, "muted_until" TIMESTAMP, "is_pinned" boolean NOT NULL DEFAULT false, "is_archived" boolean NOT NULL DEFAULT false, "notifications_enabled" boolean NOT NULL DEFAULT true, "last_read_message_id" uuid, "last_deleted_before" TIMESTAMP, "left_at" TIMESTAMP, "removed_at" TIMESTAMP, "joined_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b864798e86d0537e1670ce10b40" PRIMARY KEY ("participant_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."conversations_type_enum" AS ENUM('direct', 'group')`);
        await queryRunner.query(`CREATE TABLE "conversations" ("conversation_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "estate_id" uuid NOT NULL, "created_by_user_id" uuid NOT NULL, "type" "public"."conversations_type_enum" NOT NULL DEFAULT 'direct', "title" character varying, "photo_url" character varying, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c00ef2d6a90778048c6b8150819" PRIMARY KEY ("conversation_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."reports_category_enum" AS ENUM('Maintenance', 'Security', 'Noise/Nuisance', 'Water', 'Power', 'Cleaning', 'Parking', 'Billing', 'Other')`);
        await queryRunner.query(`CREATE TYPE "public"."reports_urgency_enum" AS ENUM('Low', 'Medium', 'High', 'Emergency')`);
        await queryRunner.query(`CREATE TYPE "public"."reports_contact_preference_enum" AS ENUM('In-app only', 'Phone', 'Email')`);
        await queryRunner.query(`CREATE TYPE "public"."reports_status_enum" AS ENUM('Open', 'Acknowledged', 'In Progress', 'Waiting on Resident', 'Resolved', 'Closed', 'Reopened')`);
        await queryRunner.query(`CREATE TABLE "reports" ("report_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "estate_id" uuid NOT NULL, "category" "public"."reports_category_enum" NOT NULL, "subject" character varying NOT NULL, "details" character varying NOT NULL, "location" character varying, "urgency" "public"."reports_urgency_enum" NOT NULL DEFAULT 'Medium', "contact_preference" "public"."reports_contact_preference_enum" NOT NULL DEFAULT 'In-app only', "attachments" jsonb, "occurred_on" TIMESTAMP, "anonymize_report" boolean NOT NULL DEFAULT false, "allow_sharing" boolean NOT NULL DEFAULT true, "status" "public"."reports_status_enum" NOT NULL DEFAULT 'Open', "assigned_to" character varying, "sla_target" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e5cb9f2cacc967a3de2f6635323" PRIMARY KEY ("report_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."lost_found_items_item_type_enum" AS ENUM('Lost', 'Found')`);
        await queryRunner.query(`CREATE TABLE "lost_found_items" ("lostfound_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sender_user_id" uuid NOT NULL, "estate_id" uuid NOT NULL, "description" character varying NOT NULL, "item_type" "public"."lost_found_items_item_type_enum" NOT NULL, "location" character varying, "contact_info" character varying, "image_url" character varying, "date_reported" TIMESTAMP NOT NULL, CONSTRAINT "PK_7c5b275237bb32c75ef24f3adb0" PRIMARY KEY ("lostfound_id"))`);
        await queryRunner.query(`CREATE TABLE "user_deleted_alerts" ("deleted_alert_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "alert_id" uuid NOT NULL, "deleted_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7a80cab0e86882e93026221e2f1" PRIMARY KEY ("deleted_alert_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ec662729d5d5aaa7b6ba45529e" ON "user_deleted_alerts" ("user_id", "alert_id") `);
        await queryRunner.query(`CREATE TYPE "public"."alerts_alert_type_enum" AS ENUM('general', 'emergency', 'maintenance', 'security', 'utility')`);
        await queryRunner.query(`CREATE TYPE "public"."alerts_urgency_level_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`CREATE TABLE "alerts" ("alert_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sender_user_id" uuid NOT NULL, "message" character varying NOT NULL, "alert_type" "public"."alerts_alert_type_enum" NOT NULL DEFAULT 'general', "urgency_level" "public"."alerts_urgency_level_enum" NOT NULL DEFAULT 'medium', "recipients" jsonb NOT NULL, "timestamp" TIMESTAMP NOT NULL, CONSTRAINT "PK_b58263d5bb1ef9464b2cf8da9e5" PRIMARY KEY ("alert_id"))`);
        await queryRunner.query(`CREATE TABLE "bank_service_charge_files" ("bsc_file_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bsc_id" uuid NOT NULL, "file_url" character varying NOT NULL, "uploaded_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5b8695d88d9ab83d9118464c3db" PRIMARY KEY ("bsc_file_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."bank_service_charges_payment_frequency_enum" AS ENUM('monthly', 'quarterly', 'yearly')`);
        await queryRunner.query(`CREATE TABLE "bank_service_charges" ("bsc_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "service_charge" numeric(10,2) NOT NULL, "paid_charge" numeric(10,2) NOT NULL, "outstanding_charge" numeric(10,2) NOT NULL, "payment_frequency" "public"."bank_service_charges_payment_frequency_enum" NOT NULL, "bank_name" character varying NOT NULL, "account_name" character varying NOT NULL, "account_number" character varying NOT NULL, "is_validated" boolean NOT NULL DEFAULT false, "validated_at" TIMESTAMP, "validated_by" character varying, "validation_notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fdaac72e15dd7f5780285420104" PRIMARY KEY ("bsc_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."announcements_announcement_type_enum" AS ENUM('general', 'payment_reminder', 'maintenance', 'event', 'security', 'urgent')`);
        await queryRunner.query(`CREATE TYPE "public"."announcements_recipient_type_enum" AS ENUM('all_residents', 'security_personnel', 'single_user', 'specific_residents')`);
        await queryRunner.query(`CREATE TABLE "announcements" ("announcement_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sender_user_id" uuid NOT NULL, "estate_id" uuid NOT NULL, "title" character varying NOT NULL, "message" text NOT NULL, "announcement_type" "public"."announcements_announcement_type_enum" NOT NULL DEFAULT 'general', "recipient_type" "public"."announcements_recipient_type_enum" NOT NULL, "target_user_ids" jsonb, "payment_details" jsonb, "image_urls" jsonb, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e6a88fded26412583072e5f745f" PRIMARY KEY ("announcement_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_43e2eda0522c7372f9a0ca8b6b" ON "announcements" ("sender_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d76c5877a1fbe21de719998796" ON "announcements" ("estate_id", "created_at") `);
        await queryRunner.query(`ALTER TABLE "device_tokens" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD "expired_date" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD "granted_by_admin" character varying`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD "is_free_subscription" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "user_profiles" ADD "isSubscribe" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "user_profiles" ADD "estate_id" character varying`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "type"`);
        await queryRunner.query(`CREATE TYPE "public"."plans_type_enum" AS ENUM('normal', 'family')`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "type" "public"."plans_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "billing_cycle"`);
        await queryRunner.query(`CREATE TYPE "public"."plans_billing_cycle_enum" AS ENUM('monthly', 'yearly')`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "billing_cycle" "public"."plans_billing_cycle_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('pending', 'active', 'expired', 'paused', 'canceled')`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('pending', 'success', 'failed')`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "status" "public"."payments_status_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "user_profiles" ALTER COLUMN "user_id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "user_profiles" DROP COLUMN "role"`);
        await queryRunner.query(`CREATE TYPE "public"."user_profiles_role_enum" AS ENUM('Residence', 'Security Personnel', 'Admin', 'Super Admin')`);
        await queryRunner.query(`ALTER TABLE "user_profiles" ADD "role" "public"."user_profiles_role_enum" NOT NULL DEFAULT 'Residence'`);
        await queryRunner.query(`ALTER TABLE "user_profiles" DROP COLUMN "apartment_type"`);
        await queryRunner.query(`CREATE TYPE "public"."user_profiles_apartment_type_enum" AS ENUM('Studio', '1-Bedroom', '2-Bedroom', '3-Bedroom', '4-Bedroom', 'Penthouse', 'Duplex')`);
        await queryRunner.query(`ALTER TABLE "user_profiles" ADD "apartment_type" "public"."user_profiles_apartment_type_enum"`);
        await queryRunner.query(`ALTER TABLE "device_tokens" DROP COLUMN "platform"`);
        await queryRunner.query(`CREATE TYPE "public"."device_tokens_platform_enum" AS ENUM('android', 'ios', 'web')`);
        await queryRunner.query(`ALTER TABLE "device_tokens" ADD "platform" "public"."device_tokens_platform_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('pending', 'active', 'suspended')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "status" "public"."users_status_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP COLUMN "direction"`);
        await queryRunner.query(`CREATE TYPE "public"."wallet_transactions_direction_enum" AS ENUM('credit', 'debit')`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD "direction" "public"."wallet_transactions_direction_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP COLUMN "purpose"`);
        await queryRunner.query(`CREATE TYPE "public"."wallet_transactions_purpose_enum" AS ENUM('top_up', 'subscription_payment', 'utility_payment', 'service_charge_payment', 'refund', 'transfer')`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD "purpose" "public"."wallet_transactions_purpose_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."wallet_transactions_status_enum" AS ENUM('pending', 'success', 'failed')`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD "status" "public"."wallet_transactions_status_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`CREATE INDEX "IDX_1a15756e257e0eaf01edc85645" ON "subscriptions" ("user_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_866ddee0e17d9385b4e3b86851" ON "payments" ("reference") `);
        await queryRunner.query(`CREATE INDEX "IDX_c47f7966fb8af1fbfa916e2561" ON "device_tokens" ("user_id", "platform") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cf1a3218f2a87daf675830a0a7" ON "access_codes" ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4b3d5cb7b4480ca1c3c367ebb4" ON "wallet_transactions" ("reference") `);
        await queryRunner.query(`ALTER TABLE "provider_photos" ADD CONSTRAINT "FK_bc9ce2a637e789d71a187f66214" FOREIGN KEY ("provider_id") REFERENCES "providers"("provider_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_reviews" ADD CONSTRAINT "FK_e6519295886c9b94d9f04de620c" FOREIGN KEY ("provider_id") REFERENCES "providers"("provider_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "providers" ADD CONSTRAINT "FK_c5674c2eab41d03d6570e39695c" FOREIGN KEY ("service_id") REFERENCES "services"("service_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "providers" ADD CONSTRAINT "FK_5df8ccf9ae71da58c7efbd44dcb" FOREIGN KEY ("admin_user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "providers" ADD CONSTRAINT "FK_cb6315f25dc25cbaecaa1ee6451" FOREIGN KEY ("estate_id") REFERENCES "estates"("estate_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "family_members" ADD CONSTRAINT "FK_610cd7909580fea972f54f50108" FOREIGN KEY ("family_group_id") REFERENCES "family_groups"("family_group_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "family_members" ADD CONSTRAINT "FK_081fe336d41be74c68b81e8b6d7" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "family_members" ADD CONSTRAINT "FK_f1bf661c32e10d66c58d617a213" FOREIGN KEY ("added_by_user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "family_groups" ADD CONSTRAINT "FK_bdb7f702b6bf965a745fea102be" FOREIGN KEY ("head_user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "family_groups" ADD CONSTRAINT "FK_989f51f66ec4461d24cd0dbcd02" FOREIGN KEY ("plan_id") REFERENCES "plans"("plan_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_d0a95ef8a28188364c546eb65c1" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_e45fca5d912c3a2fab512ac25dc" FOREIGN KEY ("plan_id") REFERENCES "plans"("plan_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_7037ad3831ecf5632ba34b0cad4" FOREIGN KEY ("last_renewal_payment_id") REFERENCES "payments"("payment_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_427785468fb7d2733f59e7d7d39" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_e92b64ae70df3f2453392dc44fd" FOREIGN KEY ("provider_id") REFERENCES "payment_providers"("provider_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "utility_payments" ADD CONSTRAINT "FK_df8a375556082ead6a6876504e7" FOREIGN KEY ("utility_bill_id") REFERENCES "utility_bills"("utility_bill_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "utility_payments" ADD CONSTRAINT "FK_3b9658702937ba78a70bcc2904b" FOREIGN KEY ("payment_id") REFERENCES "payments"("payment_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "utility_bills" ADD CONSTRAINT "FK_3de1dbecd10b2b502ff4d4940fb" FOREIGN KEY ("utility_account_id") REFERENCES "utility_accounts"("utility_account_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "utility_accounts" ADD CONSTRAINT "FK_e91f616f65d864ab2ade2f16fb2" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "utility_accounts" ADD CONSTRAINT "FK_f65f8945f49604a52f523f815c3" FOREIGN KEY ("estate_id") REFERENCES "estates"("estate_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "utility_accounts" ADD CONSTRAINT "FK_d3adc9ad394e49c58eec883aac9" FOREIGN KEY ("utility_provider_id") REFERENCES "utility_providers"("utility_provider_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_reactions" ADD CONSTRAINT "FK_ce61e365d81a9dfc15cd36513b0" FOREIGN KEY ("message_id") REFERENCES "messages"("message_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_reactions" ADD CONSTRAINT "FK_b6d3eda2f99b64016d6a4cf112f" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("conversation_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_b183972e0b84c9022884433195e" FOREIGN KEY ("sender_user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_7f87cbb925b1267778a7f4c5d67" FOREIGN KEY ("reply_to_message_id") REFERENCES "messages"("message_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "FK_1559e8a16b828f2e836a2312800" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("conversation_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "FK_377d4041a495b81ee1a85ae026f" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "FK_6cb944b185d650d33d9b5ee1bb1" FOREIGN KEY ("last_read_message_id") REFERENCES "messages"("message_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_71b0b9f615e02dc0e60f4e40bbf" FOREIGN KEY ("estate_id") REFERENCES "estates"("estate_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_c039c6d53a2f83f5d0a6dc160ca" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_ca7a21eb95ca4625bd5eaef7e0c" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_7a10e2ce75ac4e805872b7ebaaf" FOREIGN KEY ("estate_id") REFERENCES "estates"("estate_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lost_found_items" ADD CONSTRAINT "FK_d065a2eb013aa4012e3c2cf5a80" FOREIGN KEY ("sender_user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lost_found_items" ADD CONSTRAINT "FK_ea9eb7a522d4189ff920fd642d2" FOREIGN KEY ("estate_id") REFERENCES "estates"("estate_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_profiles" ADD CONSTRAINT "FK_6ca9503d77ae39b4b5a6cc3ba88" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "device_tokens" ADD CONSTRAINT "FK_17e1f528b993c6d55def4cf5bea" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "access_codes" ADD CONSTRAINT "FK_1b95b5722b3181094e0d7343d8c" FOREIGN KEY ("creator_user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_deleted_alerts" ADD CONSTRAINT "FK_6fbee870cb284eb7db2e29aa01c" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_deleted_alerts" ADD CONSTRAINT "FK_5226e09d63d4512baacde0a1728" FOREIGN KEY ("alert_id") REFERENCES "alerts"("alert_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD CONSTRAINT "FK_690f6018082a5b2ca8c7de78959" FOREIGN KEY ("sender_user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bank_service_charge_files" ADD CONSTRAINT "FK_33881de1e5dec4b26999ae2ded4" FOREIGN KEY ("bsc_id") REFERENCES "bank_service_charges"("bsc_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bank_service_charges" ADD CONSTRAINT "FK_6fae038b676dfa113f58005cf79" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD CONSTRAINT "FK_c57d19129968160f4db28fc8b28" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("wallet_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_92558c08091598f7a4439586cda" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcements" ADD CONSTRAINT "FK_43e2eda0522c7372f9a0ca8b6b3" FOREIGN KEY ("sender_user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcements" ADD CONSTRAINT "FK_189590e1850a31985616041b8d0" FOREIGN KEY ("estate_id") REFERENCES "estates"("estate_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "announcements" DROP CONSTRAINT "FK_189590e1850a31985616041b8d0"`);
        await queryRunner.query(`ALTER TABLE "announcements" DROP CONSTRAINT "FK_43e2eda0522c7372f9a0ca8b6b3"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_92558c08091598f7a4439586cda"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP CONSTRAINT "FK_c57d19129968160f4db28fc8b28"`);
        await queryRunner.query(`ALTER TABLE "bank_service_charges" DROP CONSTRAINT "FK_6fae038b676dfa113f58005cf79"`);
        await queryRunner.query(`ALTER TABLE "bank_service_charge_files" DROP CONSTRAINT "FK_33881de1e5dec4b26999ae2ded4"`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP CONSTRAINT "FK_690f6018082a5b2ca8c7de78959"`);
        await queryRunner.query(`ALTER TABLE "user_deleted_alerts" DROP CONSTRAINT "FK_5226e09d63d4512baacde0a1728"`);
        await queryRunner.query(`ALTER TABLE "user_deleted_alerts" DROP CONSTRAINT "FK_6fbee870cb284eb7db2e29aa01c"`);
        await queryRunner.query(`ALTER TABLE "access_codes" DROP CONSTRAINT "FK_1b95b5722b3181094e0d7343d8c"`);
        await queryRunner.query(`ALTER TABLE "device_tokens" DROP CONSTRAINT "FK_17e1f528b993c6d55def4cf5bea"`);
        await queryRunner.query(`ALTER TABLE "user_profiles" DROP CONSTRAINT "FK_6ca9503d77ae39b4b5a6cc3ba88"`);
        await queryRunner.query(`ALTER TABLE "lost_found_items" DROP CONSTRAINT "FK_ea9eb7a522d4189ff920fd642d2"`);
        await queryRunner.query(`ALTER TABLE "lost_found_items" DROP CONSTRAINT "FK_d065a2eb013aa4012e3c2cf5a80"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_7a10e2ce75ac4e805872b7ebaaf"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_ca7a21eb95ca4625bd5eaef7e0c"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_c039c6d53a2f83f5d0a6dc160ca"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_71b0b9f615e02dc0e60f4e40bbf"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "FK_6cb944b185d650d33d9b5ee1bb1"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "FK_377d4041a495b81ee1a85ae026f"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "FK_1559e8a16b828f2e836a2312800"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_7f87cbb925b1267778a7f4c5d67"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_b183972e0b84c9022884433195e"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23"`);
        await queryRunner.query(`ALTER TABLE "message_reactions" DROP CONSTRAINT "FK_b6d3eda2f99b64016d6a4cf112f"`);
        await queryRunner.query(`ALTER TABLE "message_reactions" DROP CONSTRAINT "FK_ce61e365d81a9dfc15cd36513b0"`);
        await queryRunner.query(`ALTER TABLE "utility_accounts" DROP CONSTRAINT "FK_d3adc9ad394e49c58eec883aac9"`);
        await queryRunner.query(`ALTER TABLE "utility_accounts" DROP CONSTRAINT "FK_f65f8945f49604a52f523f815c3"`);
        await queryRunner.query(`ALTER TABLE "utility_accounts" DROP CONSTRAINT "FK_e91f616f65d864ab2ade2f16fb2"`);
        await queryRunner.query(`ALTER TABLE "utility_bills" DROP CONSTRAINT "FK_3de1dbecd10b2b502ff4d4940fb"`);
        await queryRunner.query(`ALTER TABLE "utility_payments" DROP CONSTRAINT "FK_3b9658702937ba78a70bcc2904b"`);
        await queryRunner.query(`ALTER TABLE "utility_payments" DROP CONSTRAINT "FK_df8a375556082ead6a6876504e7"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_e92b64ae70df3f2453392dc44fd"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_427785468fb7d2733f59e7d7d39"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_7037ad3831ecf5632ba34b0cad4"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_e45fca5d912c3a2fab512ac25dc"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_d0a95ef8a28188364c546eb65c1"`);
        await queryRunner.query(`ALTER TABLE "family_groups" DROP CONSTRAINT "FK_989f51f66ec4461d24cd0dbcd02"`);
        await queryRunner.query(`ALTER TABLE "family_groups" DROP CONSTRAINT "FK_bdb7f702b6bf965a745fea102be"`);
        await queryRunner.query(`ALTER TABLE "family_members" DROP CONSTRAINT "FK_f1bf661c32e10d66c58d617a213"`);
        await queryRunner.query(`ALTER TABLE "family_members" DROP CONSTRAINT "FK_081fe336d41be74c68b81e8b6d7"`);
        await queryRunner.query(`ALTER TABLE "family_members" DROP CONSTRAINT "FK_610cd7909580fea972f54f50108"`);
        await queryRunner.query(`ALTER TABLE "providers" DROP CONSTRAINT "FK_cb6315f25dc25cbaecaa1ee6451"`);
        await queryRunner.query(`ALTER TABLE "providers" DROP CONSTRAINT "FK_5df8ccf9ae71da58c7efbd44dcb"`);
        await queryRunner.query(`ALTER TABLE "providers" DROP CONSTRAINT "FK_c5674c2eab41d03d6570e39695c"`);
        await queryRunner.query(`ALTER TABLE "provider_reviews" DROP CONSTRAINT "FK_e6519295886c9b94d9f04de620c"`);
        await queryRunner.query(`ALTER TABLE "provider_photos" DROP CONSTRAINT "FK_bc9ce2a637e789d71a187f66214"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b3d5cb7b4480ca1c3c367ebb4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf1a3218f2a87daf675830a0a7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c47f7966fb8af1fbfa916e2561"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_866ddee0e17d9385b4e3b86851"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1a15756e257e0eaf01edc85645"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_transactions_status_enum"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD "status" character varying NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP COLUMN "purpose"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_transactions_purpose_enum"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD "purpose" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP COLUMN "direction"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_transactions_direction_enum"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD "direction" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "status" character varying NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "device_tokens" DROP COLUMN "platform"`);
        await queryRunner.query(`DROP TYPE "public"."device_tokens_platform_enum"`);
        await queryRunner.query(`ALTER TABLE "device_tokens" ADD "platform" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_profiles" DROP COLUMN "apartment_type"`);
        await queryRunner.query(`DROP TYPE "public"."user_profiles_apartment_type_enum"`);
        await queryRunner.query(`ALTER TABLE "user_profiles" ADD "apartment_type" character varying`);
        await queryRunner.query(`ALTER TABLE "user_profiles" DROP COLUMN "role"`);
        await queryRunner.query(`DROP TYPE "public"."user_profiles_role_enum"`);
        await queryRunner.query(`ALTER TABLE "user_profiles" ADD "role" character varying NOT NULL DEFAULT 'Residence'`);
        await queryRunner.query(`ALTER TABLE "user_profiles" ALTER COLUMN "user_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "status" character varying NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD "status" character varying NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "billing_cycle"`);
        await queryRunner.query(`DROP TYPE "public"."plans_billing_cycle_enum"`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "billing_cycle" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."plans_type_enum"`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_profiles" DROP COLUMN "estate_id"`);
        await queryRunner.query(`ALTER TABLE "user_profiles" DROP COLUMN "isSubscribe"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP COLUMN "is_free_subscription"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP COLUMN "granted_by_admin"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP COLUMN "expired_date"`);
        await queryRunner.query(`ALTER TABLE "device_tokens" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d76c5877a1fbe21de719998796"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_43e2eda0522c7372f9a0ca8b6b"`);
        await queryRunner.query(`DROP TABLE "announcements"`);
        await queryRunner.query(`DROP TYPE "public"."announcements_recipient_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."announcements_announcement_type_enum"`);
        await queryRunner.query(`DROP TABLE "bank_service_charges"`);
        await queryRunner.query(`DROP TYPE "public"."bank_service_charges_payment_frequency_enum"`);
        await queryRunner.query(`DROP TABLE "bank_service_charge_files"`);
        await queryRunner.query(`DROP TABLE "alerts"`);
        await queryRunner.query(`DROP TYPE "public"."alerts_urgency_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."alerts_alert_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ec662729d5d5aaa7b6ba45529e"`);
        await queryRunner.query(`DROP TABLE "user_deleted_alerts"`);
        await queryRunner.query(`DROP TABLE "lost_found_items"`);
        await queryRunner.query(`DROP TYPE "public"."lost_found_items_item_type_enum"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TYPE "public"."reports_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reports_contact_preference_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reports_urgency_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reports_category_enum"`);
        await queryRunner.query(`DROP TABLE "conversations"`);
        await queryRunner.query(`DROP TYPE "public"."conversations_type_enum"`);
        await queryRunner.query(`DROP TABLE "conversation_participants"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TYPE "public"."messages_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."messages_type_enum"`);
        await queryRunner.query(`DROP TABLE "message_reactions"`);
        await queryRunner.query(`DROP TABLE "utility_accounts"`);
        await queryRunner.query(`DROP TABLE "utility_bills"`);
        await queryRunner.query(`DROP TYPE "public"."utility_bills_status_enum"`);
        await queryRunner.query(`DROP TABLE "utility_payments"`);
        await queryRunner.query(`DROP TABLE "utility_providers"`);
        await queryRunner.query(`DROP TYPE "public"."utility_providers_category_enum"`);
        await queryRunner.query(`DROP TABLE "providers"`);
        await queryRunner.query(`DROP TABLE "provider_reviews"`);
        await queryRunner.query(`DROP TABLE "provider_photos"`);
        await queryRunner.query(`DROP TABLE "services"`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_wallets_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD CONSTRAINT "FK_wallet_transactions_wallet_id" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("wallet_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "access_codes" ADD CONSTRAINT "FK_access_codes_creator_user_id" FOREIGN KEY ("creator_user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "device_tokens" ADD CONSTRAINT "FK_device_tokens_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_profiles" ADD CONSTRAINT "FK_user_profiles_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payments_provider_id" FOREIGN KEY ("provider_id") REFERENCES "payment_providers"("provider_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payments_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_subscriptions_payment_id" FOREIGN KEY ("last_renewal_payment_id") REFERENCES "payments"("payment_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_subscriptions_plan_id" FOREIGN KEY ("plan_id") REFERENCES "plans"("plan_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_subscriptions_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "family_groups" ADD CONSTRAINT "FK_family_groups_plan_id" FOREIGN KEY ("plan_id") REFERENCES "plans"("plan_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "family_groups" ADD CONSTRAINT "FK_family_groups_head_user_id" FOREIGN KEY ("head_user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "family_members" ADD CONSTRAINT "FK_family_members_added_by_user_id" FOREIGN KEY ("added_by_user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "family_members" ADD CONSTRAINT "FK_family_members_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "family_members" ADD CONSTRAINT "FK_family_members_family_group_id" FOREIGN KEY ("family_group_id") REFERENCES "family_groups"("family_group_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
